<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RwtIsRimWorldMod>true</RwtIsRimWorldMod>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>TaskInterrupt</AssemblyName>
    <RootNamespace>TaskInterrupt</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\1.6\Assemblies\</OutputPath>
    <RwtUseHarmony>true</RwtUseHarmony>
    <RwtUseSpine>true</RwtUseSpine>
    <RwtUseUnityImGui>true</RwtUseUnityImGui>
  </PropertyGroup>
</Project>
